#告知当前使用的是交叉编译方式，必须配置
SET(CMAKE_SYSTEM_NAME Linux)
SET(TOOLCHAIN_DIR "/opt/hisi-linux/x86-arm/arm-hisiv400-linux/target")

set(CMAKE_CXX_COMPILER ${TOOLCHAIN_DIR}/bin/arm-hisiv400-linux-g++)
set(CMAKE_C_COMPILER   ${TOOLCHAIN_DIR}/bin/arm-hisiv400-linux-gcc)

#告诉cmake是进行交叉编译
set(CMAKE_CROSSCOMPILING TRUE)

# SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} --sysroot=${MYSYSROOT}" CACHE INTERNAL "" FORCE)
# SET(CMAKE_C_LINK_FLAGS "${CMAKE_C_LINK_FLAGS} --sysroot=${MYSYSROOT}" CACHE INTERNAL "" FORCE)
# SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} --sysroot=${MYSYSROOT}" CACHE INTERNAL "" FORCE)
# SET(CMAKE_CXX_LINK_FLAGS "${CMAKE_CXX_LINK_FLAGS} --sysroot=${MYSYSROOT}" CACHE INTERNAL "" FORCE)
# set(GNU_FLAGS "-mfpu=vfp -fPIC")
# set(CMAKE_CXX_FLAGS "${GNU_FLAGS} ")
# set(CMAKE_C_FLAGS "${GNU_FLAGS}  ")

#指定交叉编译环境安装目录...
SET( CMAKE_FIND_ROOT_PATH  ${TOOLCHAIN_DIR})

#从来不在指定目录下查找工具程序
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)

#只在指定目录下查找库文件
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)

#只在指定目录下查找头文件
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

SET(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)